from django.db import models


class ExchangesOptions(models.TextChoices):
    ACX = "acx"
    AOFEX = "aofex"
    BCEX = "bcex"
    BEQUANT = "bequant"
    BIBOX = "bibox"
    BIGONE = "bigone"
    BINANCE = "binance"
    BINANCEUS = "binanceus"
    BIT2C = "bit2c"
    BITBANK = "bitbank"
    BITBAY = "bitbay"
    BITCOINCOM = "bitcoincom"
    BITFINEX = "bitfinex"
    BITFINEX2 = "bitfinex2"
    BITFLYER = "bitflyer"
    BITFOREX = "bitforex"
    BITGET = "bitget"
    BITHUMB = "bithumb"
    BITKK = "bitkk"
    BITMART = "bitmart"
    BITMAX = "bitmax"
    BITMEX = "bitmex"
    BITPANDA = "bitpanda"
    BITSO = "bitso"
    BITSTAMP = "bitstamp"
    BITSTAMP1 = "bitstamp1"
    BITTREX = "bittrex"
    BITVAVO = "bitvavo"
    BITZ = "bitz"
    BL3P = "bl3p"
    BLEUTRADE = "bleutrade"
    BRAZILIEX = "braziliex"
    BTCALPHA = "btcalpha"
    BTCBOX = "btcbox"
    BTCMARKETS = "btcmarkets"
    BTCTRADEUA = "btctradeua"
    BTCTURK = "btcturk"
    BUDA = "buda"
    BW = "bw"
    BYBIT = "bybit"
    BYTETRADE = "bytetrade"
    CDAX = "cdax"
    CEX = "cex"
    CHILEBIT = "chilebit"
    COINBASE = "coinbase"
    COINBASEPRIME = "coinbaseprime"
    COINBASEPRO = "coinbasepro"
    COINCHECK = "coincheck"
    COINEGG = "coinegg"
    COINEX = "coinex"
    COINFALCON = "coinfalcon"
    COINFLOOR = "coinfloor"
    COINGI = "coingi"
    COINMARKETCAP = "coinmarketcap"
    COINMATE = "coinmate"
    COINONE = "coinone"
    COINSPOT = "coinspot"
    CREX24 = "crex24"
    CURRENCYCOM = "currencycom"
    DELTA = "delta"
    DERIBIT = "deribit"
    DIGIFINEX = "digifinex"
    DSX = "dsx"
    ETERBASE = "eterbase"
    EXMO = "exmo"
    EXX = "exx"
    FCOIN = "fcoin"
    FCOINJP = "fcoinjp"
    FLOWBTC = "flowbtc"
    FOXBIT = "foxbit"
    FTX = "ftx"
    GATEIO = "gateio"
    GEMINI = "gemini"
    GOPAX = "gopax"
    HBTC = "hbtc"
    HITBTC = "hitbtc"
    HOLLAEX = "hollaex"
    HUOBIJP = "huobijp"
    HUOBIPRO = "huobipro"
    ICE3X = "ice3x"
    IDEX = "idex"
    INDEPENDENTRESERVE = "independentreserve"
    INDODAX = "indodax"
    ITBIT = "itbit"
    KRAKEN = "kraken"
    KUCOIN = "kucoin"
    KUNA = "kuna"
    LAKEBTC = "lakebtc"
    LATOKEN = "latoken"
    LBANK = "lbank"
    LIQUID = "liquid"
    LIVECOIN = "livecoin"
    LUNO = "luno"
    LYKKE = "lykke"
    MERCADO = "mercado"
    MIXCOINS = "mixcoins"
    NOVADAX = "novadax"
    OCEANEX = "oceanex"
    OKCOIN = "okcoin"
    OKEX = "okex"
    PAYMIUM = "paymium"
    PHEMEX = "phemex"
    POLONIEX = "poloniex"
    PROBIT = "probit"
    QTRADE = "qtrade"
    RIGHTBTC = "rightbtc"
    RIPIO = "ripio"
    SOUTHXCHANGE = "southxchange"
    STEX = "stex"
    SURBITCOIN = "surbitcoin"
    THEROCK = "therock"
    TIDEBIT = "tidebit"
    TIDEX = "tidex"
    TIMEX = "timex"
    UPBIT = "upbit"
    VAULTORO = "vaultoro"
    VBTC = "vbtc"
    VCC = "vcc"
    WAVESEXCHANGE = "wavesexchange"
    WHITEBIT = "whitebit"
    XBTCE = "xbtce"
    XENA = "xena"
    YOBIT = "yobit"
    ZAIF = "zaif"
    ZB = "zb"


class Timeframes(models.TextChoices):
    MINUTE_1 = "1m"
    MINUTE_3 = "3m"
    MINUTE_5 = "5m"
    MINUTE_15 = "15m"
    MINUTE_30 = "30m"
    HOUR_1 = "1h"
    HOUR_2 = "2h"
    HOUR_4 = "4h"
    HOUR_6 = "6h"
    HOUR_8 = "8h"
    HOUR_12 = "12h"
    DAY_1 = "1d"
    DAY_3 = "3d"
    WEEK_1 = "1w"
    MONTH_1 = "1M"


# ORDER_TYPE_CHOICE
class OrderType(models.TextChoices):
    MARKET = "market"
    LIMIT = "limit"


# SIDE_CHOICE
class OrderSide(models.TextChoices):
    SIDE_BUY = "buy"
    SIDE_SELL = "sell"


# STATUS_CHOICE
class OrderStatus(models.TextChoices):
    OPEN = "open"
    CLOSED = "closed"
    CANCELED = "canceled"
    EXPIRED = "expired"
    REJECTED = "rejected"
    NOT_MIN_NOTIONAL = "not min notional"
