# Generated by Django 3.0.5 on 2020-06-18 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trading_bot", "0002_auto_20200513_1942"),
    ]

    operations = [
        migrations.AddField(
            model_name="trade",
            name="re_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="re_order",
                to="trading_bot.Order",
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order",
                to="trading_bot.Order",
            ),
        ),
    ]
