# Generated by Django 3.0.5 on 2020-07-08 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trading_bot", "0002_auto_20200708_1557"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot",
            name="max_amount",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=30, null=True
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="min_rise",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=30, null=True
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="stop_loss",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=30, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="last_price_tick",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=30, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="market",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="trading_bot.Market",
            ),
        ),
    ]
