# Generated by Django 3.0.5 on 2020-06-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0003_auto_20200618_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fee_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fee_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='fee_rate',
        ),
    ]
