# Generated by Django 3.0.5 on 2020-07-09 11:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_bot", "0003_auto_20200708_1941"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="default_fee_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal(
                    "0.1000000000000000055511151231257827021181583404541015625"
                ),
                max_digits=30,
            ),
        ),
    ]
