# Generated by Django 3.0.5 on 2020-06-19 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trading_bot", "0005_auto_20200619_0930"),
    ]

    operations = [
        migrations.RemoveField(model_name="trade", name="re_order",),
        migrations.AddField(
            model_name="order",
            name="next_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trading_bot.Order",
            ),
        ),
        migrations.AlterField(
            model_name="trade",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trade_order",
                to="trading_bot.Order",
            ),
        ),
    ]
