# Generated by Django 3.0.5 on 2020-06-19 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trading_bot", "0007_ordererrorlog"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="exchange",),
        migrations.AddField(
            model_name="order",
            name="fee_cost",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=30, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="fee_currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="trading_bot.Currency",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="fee_rate",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=30, null=True
            ),
        ),
    ]
