# Generated by Django 3.0.5 on 2020-06-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_bot", "0009_saving"),
    ]

    operations = [
        migrations.AddField(
            model_name="bot", name="active", field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("closed", "Closed"),
                    ("canceled", "Canceled"),
                    ("expired", "Expired"),
                    ("rejected", "Rejected"),
                    ("not min notional", "Not Min Notional"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
